print("Hello user")
term_of_endearment=input("what do you call you crush: ")
first_name=input("what is your first name: ")
last_name=input("what is your last name: ")
place=input("give me a place: ") 
color=input("give me a color: ")
number=input("give me a number: ")
verb=input("give me a verb: ")
print("Hey,"+term_of_endearment+" It is me. What up. You know "+first_name+ ". " +first_name + " " +last_name + ". From the " + place + ". Two Fridays ago. I was the hot guy in the " +color+ "  parachute pants. I paid the bus boy " + number+ " dollars to give me your information. I was wondering if maybe you would like to go out with me. Please do not call the " + verb + " department. Alright I will " + verb + ". So that is a no?")